-- ============================================================
-- El Pantano — Migration 002: FAQ field for articles
-- Run in Supabase Dashboard > SQL Editor
-- ============================================================

-- Add FAQ column to articles table
-- Stores an array of {question, answer} objects generated by N8N
ALTER TABLE articles
  ADD COLUMN IF NOT EXISTS faq JSONB DEFAULT '[]'::jsonb;

-- Example value:
-- [
--   {"question": "¿Qué es X?", "answer": "X es..."},
--   {"question": "¿Cómo funciona Y?", "answer": "Y funciona..."}
-- ]
